// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 12.0.0.0
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace YP.CodeGen.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class ControllerTemplate : ControllerTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Linq;\r\nusing Syste" +
                    "m.Net.Http;\r\nusing System.Text.RegularExpressions;\r\nusing System.Web.Http;\r\nusin" +
                    "g System.Web.Http.Cors;\r\nusing ");
            
            #line 13 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_projectName));
            
            #line default
            #line hidden
            this.Write(".Entity.Model;\r\nusing ");
            
            #line 14 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_projectName));
            
            #line default
            #line hidden
            this.Write(".Service.");
            
            #line 14 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write(";\r\nusing YooPoon.Core.Site;\r\nusing YooPoon.WebFramework.API;\r\nusing ");
            
            #line 17 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_projectName));
            
            #line default
            #line hidden
            this.Write(".Models;\r\n\r\nnamespace ");
            
            #line 19 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_projectName));
            
            #line default
            #line hidden
            this.Write(".Controllers\r\n{\r\n\tpublic class ");
            
            #line 21 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("Controller : ApiController\r\n\t{\r\n\t\tprivate readonly I");
            
            #line 23 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("Service _");
            
            #line 23 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("Service;\r\n\r\n\t\tpublic ");
            
            #line 25 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("Controller(I");
            
            #line 25 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("Service ");
            
            #line 25 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("Service)\r\n\t\t{\r\n\t\t\t_");
            
            #line 27 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("Service = ");
            
            #line 27 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("Service;\r\n\t\t}\r\n\r\n\t\tpublic ");
            
            #line 30 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("Model Get(int id)\r\n\t\t{\r\n\t\t\tvar entity =_");
            
            #line 32 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("Service.Get");
            
            #line 32 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("ById(id);\r\n\t\t\tvar model = new ");
            
            #line 33 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("Model\r\n\t\t\t{\r\n");
            
            #line 35 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
 foreach(var filed in _entityModels){ if(filed.IsVirtual) continue;
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 36 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(filed.FieldName));
            
            #line default
            #line hidden
            this.Write(" = entity.");
            
            #line 36 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(filed.FieldName));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 36 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t};\r\n\t\t\treturn model;\r\n\t\t}\r\n\r\n\t\tpublic List<");
            
            #line 41 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("Model> Get(");
            
            #line 41 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("SearchCondition condition)\r\n\t\t{\r\n\t\t\tvar model = _");
            
            #line 43 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("Service.Get");
            
            #line 43 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("sByCondition(condition).Select(c=>new ");
            
            #line 43 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("Model\r\n\t\t\t{\r\n");
            
            #line 45 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
 foreach(var filed in _entityModels){ if(filed.IsVirtual) continue;
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 46 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(filed.FieldName));
            
            #line default
            #line hidden
            this.Write(" = c.");
            
            #line 46 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(filed.FieldName));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 47 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t}).ToList();\r\n\t\t\treturn model;\r\n\t\t}\r\n\r\n\t\tpublic bool Post(");
            
            #line 52 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("Model model)\r\n\t\t{\r\n\t\t\tvar entity = new ");
            
            #line 54 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("Entity\r\n\t\t\t{\r\n");
            
            #line 56 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
 foreach(var filed in _entityModels){ if(filed.FieldName =="Id" || filed.IsVirtual) continue;
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 57 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(filed.FieldName));
            
            #line default
            #line hidden
            this.Write(" = model.");
            
            #line 57 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(filed.FieldName));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 58 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t};\r\n\t\t\tif(_");
            
            #line 60 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("Service.Create(entity).Id > 0)\r\n\t\t\t{\r\n\t\t\t\treturn true;\r\n\t\t\t}\r\n\t\t\treturn false;\r\n\t" +
                    "\t}\r\n\r\n\t\tpublic bool Put(");
            
            #line 67 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("Model model)\r\n\t\t{\r\n\t\t\tvar entity = _");
            
            #line 69 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("Service.Get");
            
            #line 69 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("ById(model.Id);\r\n\t\t\tif(entity == null)\r\n\t\t\t\treturn false;\r\n");
            
            #line 72 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
 foreach(var filed in _entityModels){ if(filed.FieldName =="Id" || filed.IsVirtual) continue;
            
            #line default
            #line hidden
            this.Write("\t\t\tentity.");
            
            #line 73 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(filed.FieldName));
            
            #line default
            #line hidden
            this.Write(" = model.");
            
            #line 73 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(filed.FieldName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 74 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\tif(_");
            
            #line 75 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("Service.Update(entity) != null)\r\n\t\t\t\treturn true;\r\n\t\t\treturn false;\r\n\t\t}\r\n\r\n\t\tpub" +
                    "lic bool Delete(int id)\r\n\t\t{\r\n\t\t\tvar entity = _");
            
            #line 82 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("Service.Get");
            
            #line 82 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("ById(id);\r\n\t\t\tif(entity == null)\r\n\t\t\t\treturn false;\r\n\t\t\tif(_");
            
            #line 85 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("Service.Delete(entity))\r\n\t\t\t\treturn true;\r\n\t\t\treturn false;\r\n\t\t}\r\n\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class ControllerTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
