// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 12.0.0.0
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace YP.CodeGen.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using YP.CodeGen.TemplateModel;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class ServiceTemplate : ServiceTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 7 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
 var orderNames = new List<string>(); 
            
            #line default
            #line hidden
            this.Write("using System;\r\nusing System.Linq;\r\nusing YooPoon.Core.Data;\r\nusing YooPoon.Core.L" +
                    "ogging;\r\nusing ");
            
            #line 12 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_projectName));
            
            #line default
            #line hidden
            this.Write(".Entity.Model;\r\n\r\nnamespace ");
            
            #line 14 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_projectName));
            
            #line default
            #line hidden
            this.Write(".Service.");
            
            #line 14 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic class ");
            
            #line 16 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Service : I");
            
            #line 16 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Service\r\n\t{\r\n\t\tprivate readonly IRepository<");
            
            #line 18 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Entity> _");
            
            #line 18 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Repository;\r\n\t\tprivate readonly ILog _log;\r\n\r\n\t\tpublic ");
            
            #line 21 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Service(IRepository<");
            
            #line 21 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Entity> ");
            
            #line 21 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Repository,ILog log)\r\n\t\t{\r\n\t\t\t_");
            
            #line 23 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Repository = ");
            
            #line 23 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Repository;\r\n\t\t\t_log = log;\r\n\t\t}\r\n\t\t\r\n\t\tpublic ");
            
            #line 27 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Entity Create (");
            
            #line 27 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Entity entity)\r\n\t\t{\r\n\t\t\ttry\r\n            {\r\n                _");
            
            #line 31 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Repository.Insert(entity);\r\n                return entity;\r\n            }\r\n      " +
                    "      catch (Exception e)\r\n            {\r\n\t\t\t\t_log.Error(e,\"数据库操作出错\");\r\n        " +
                    "        return null;\r\n            }\r\n\t\t}\r\n\r\n\t\tpublic bool Delete(");
            
            #line 41 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Entity entity)\r\n\t\t{\r\n\t\t\ttry\r\n            {\r\n                _");
            
            #line 45 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Repository.Delete(entity);\r\n                return true;\r\n            }\r\n        " +
                    "    catch (Exception e)\r\n            {\r\n\t\t\t\t_log.Error(e,\"数据库操作出错\");\r\n          " +
                    "      return false;\r\n            }\r\n\t\t}\r\n\r\n\t\tpublic ");
            
            #line 55 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Entity Update (");
            
            #line 55 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Entity entity)\r\n\t\t{\r\n\t\t\ttry\r\n            {\r\n                _");
            
            #line 59 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Repository.Update(entity);\r\n                return entity;\r\n            }\r\n      " +
                    "      catch (Exception e)\r\n            {\r\n\t\t\t\t_log.Error(e,\"数据库操作出错\");\r\n        " +
                    "        return null;\r\n            }\r\n\t\t}\r\n\r\n\t\tpublic ");
            
            #line 69 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Entity Get");
            
            #line 69 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("ById (int id)\r\n\t\t{\r\n\t\t\ttry\r\n            {\r\n                return _");
            
            #line 73 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Repository.GetById(id);\r\n            }\r\n            catch (Exception e)\r\n        " +
                    "    {\r\n\t\t\t\t_log.Error(e,\"数据库操作出错\");\r\n                return null;\r\n            }" +
                    "\r\n\t\t}\r\n\r\n\t\tpublic IQueryable<");
            
            #line 82 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Entity> Get");
            
            #line 82 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("sByCondition(");
            
            #line 82 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("SearchCondition condition)\r\n\t\t{\r\n\t\t\tvar query = _");
            
            #line 84 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Repository.Table;\r\n\t\t\ttry\r\n\t\t\t{\r\n");
            
            #line 87 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
 foreach(var model in _sModels.OrderByDescending(c => c.Type)){ 
				if(model.Type == EnumSearchType.Range){
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (condition.");
            
            #line 89 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write("Begin.HasValue)\r\n                {\r\n                    query = query.Where(q => " +
                    "q.");
            
            #line 91 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write(">= condition.");
            
            #line 91 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write("Begin.Value);\r\n                }\r\n                if (condition.");
            
            #line 93 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write("End.HasValue)\r\n                {\r\n                    query = query.Where(q => q." +
                    "");
            
            #line 95 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write(" < condition.");
            
            #line 95 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write("End.Value);\r\n                }\r\n");
            
            #line 97 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
 }			else if(model.Type == EnumSearchType.Equal){
				if(model.SearchType =="string"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (!string.IsNullOrEmpty(condition.");
            
            #line 99 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write("))\r\n                {\r\n                    query = query.Where(q => q.");
            
            #line 101 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write(" == condition.");
            
            #line 101 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write(");\r\n                }\r\n");
            
            #line 103 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (condition.");
            
            #line 104 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write(".HasValue)\r\n                {\r\n                    query = query.Where(q => q.");
            
            #line 106 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write(" == condition.");
            
            #line 106 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write(".Value);\r\n                }\r\n");
            
            #line 108 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
 }
            
            #line default
            #line hidden
            
            #line 109 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
 }			else if(model.Type == EnumSearchType.Like){
				if(model.SearchType =="string"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (!string.IsNullOrEmpty(condition.");
            
            #line 111 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write("))\r\n                {\r\n                    query = query.Where(q => q.");
            
            #line 113 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write(".Contains(condition.");
            
            #line 113 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write("));\r\n                }\r\n");
            
            #line 115 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (condition.");
            
            #line 116 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write(".HasValue)\r\n                {\r\n                    query = query.Where(q => q.");
            
            #line 118 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write(".Contains(condition.");
            
            #line 118 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write(".Value));\r\n                }\r\n");
            
            #line 120 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 121 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
}				else if(model.Type == EnumSearchType.In){
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (condition.");
            
            #line 122 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write("s != null && condition.");
            
            #line 122 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write("s.Any())\r\n                {\r\n                    query = query.Where(q => conditi" +
                    "on.");
            
            #line 124 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write("s.Contains(q.");
            
            #line 124 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write("));\r\n                }\r\n");
            
            #line 126 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
}				else if(model.Type == EnumSearchType.Order){
 orderNames.Add(model.SearchName);}
            
            #line default
            #line hidden
            
            #line 128 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 129 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
				if(orderNames.Count() > 0){
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif(condition.OrderBy.HasValue)\r\n\t\t\t\t{\r\n\t\t\t\t\tswitch (condition.OrderBy.Value)\r" +
                    "\n                    {\r\n");
            
            #line 134 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
						foreach(var name in orderNames){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\tcase Enum");
            
            #line 135 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("SearchOrderBy.OrderBy");
            
            #line 135 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(":\r\n\t\t\t\t\t\t\tquery = condition.IsDescending?query.OrderByDescending(q=>q.");
            
            #line 136 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("):query.OrderBy(q=>q.");
            
            #line 136 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\t\t\t\tbreak;\r\n");
            
            #line 138 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("                    }\r\n\t\t\t\t\t\r\n\t\t\t\t}\r\n");
            
            #line 142 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("\t\t\t\telse\r\n\t\t\t\t{\r\n\t\t\t\t\tquery = query.OrderBy(q=>q.");
            
            #line 145 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(orderNames.First()));
            
            #line default
            #line hidden
            this.Write(@");
				}

				if (condition.Page.HasValue && condition.PageCount.HasValue)
                {
                    query = query.Skip((condition.Page.Value - 1)*condition.PageCount.Value).Take(condition.PageCount.Value);
                }
				return query;
			}
			catch(Exception e)
			{
				_log.Error(e,""数据库操作出错"");
                return null;
			}
		}

		public int Get");
            
            #line 161 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Count (");
            
            #line 161 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("SearchCondition condition)\r\n\t\t{\r\n\t\t\tvar query = _");
            
            #line 163 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Repository.Table;\r\n\t\t\ttry\r\n\t\t\t{\r\n");
            
            #line 166 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
 foreach(var model in _sModels.OrderByDescending(c => c.Type)){ 
				if(model.Type == EnumSearchType.Range){
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (condition.");
            
            #line 168 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write("Begin.HasValue)\r\n                {\r\n                    query = query.Where(q => " +
                    "q.");
            
            #line 170 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write(">= condition.");
            
            #line 170 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write("Begin.Value);\r\n                }\r\n                if (condition.");
            
            #line 172 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write("End.HasValue)\r\n                {\r\n                    query = query.Where(q => q." +
                    "");
            
            #line 174 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write(" < condition.");
            
            #line 174 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write("End.Value);\r\n                }\r\n");
            
            #line 176 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
 }			else if(model.Type == EnumSearchType.Equal){
				if(model.SearchType =="string"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (!string.IsNullOrEmpty(condition.");
            
            #line 178 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write("))\r\n                {\r\n                    query = query.Where(q => q.");
            
            #line 180 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write(" == condition.");
            
            #line 180 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write(");\r\n                }\r\n");
            
            #line 182 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (condition.");
            
            #line 183 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write(".HasValue)\r\n                {\r\n                    query = query.Where(q => q.");
            
            #line 185 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write(" == condition.");
            
            #line 185 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write(".Value);\r\n                }\r\n");
            
            #line 187 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
 }
            
            #line default
            #line hidden
            
            #line 188 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
 }			else if(model.Type == EnumSearchType.Like){
				if(model.SearchType =="string"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (!string.IsNullOrEmpty(condition.");
            
            #line 190 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write("))\r\n                {\r\n                    query = query.Where(q => q.");
            
            #line 192 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write(".Contains(condition.");
            
            #line 192 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write("));\r\n                }\r\n");
            
            #line 194 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (condition.");
            
            #line 195 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write(".HasValue)\r\n                {\r\n                    query = query.Where(q => q.");
            
            #line 197 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write(".Contains(condition.");
            
            #line 197 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write(".Value));\r\n                }\r\n");
            
            #line 199 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 200 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
}				else if(model.Type == EnumSearchType.In){
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (condition.");
            
            #line 201 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write("s != null && condition.");
            
            #line 201 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write("s.Any())\r\n                {\r\n                    query = query.Where(q => conditi" +
                    "on.");
            
            #line 203 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write("s.Contains(q.");
            
            #line 203 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.SearchName));
            
            #line default
            #line hidden
            this.Write("));\r\n                }\r\n");
            
            #line 205 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
 }
            
            #line default
            #line hidden
            
            #line 206 "D:\Project_Zerg\Dev\Code\YP.CodeGen\Templates\ServiceTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\treturn query.Count();\r\n\t\t\t}\r\n\t\t\tcatch(Exception e)\r\n\t\t\t{\r\n\t\t\t\t_log.Error(e,\"数" +
                    "据库操作出错\");\r\n                return -1;\r\n\t\t\t}\r\n\t\t}\r\n\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class ServiceTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
